Add comments to intermediates
greymatter-io/gitops-core pull request #57
Opened 2022-08-16 14:20 UTC by tilleryd

2022-08-16 16:14 UTC, dontlaugh requested changes
A few changes. Looks good overall.

Avoid "this" and "that" when introducing a big complicated stanza. Call the stanza by name.

2022-08-16 16:14 UTC, dontlaugh commented on gm/intermediates.cue
> +	// Enable this to turn on secure traffic to the service.
```suggestion
	// Set _force_https to true to turn on secure traffic to the service.
```

2022-08-16 16:14 UTC, dontlaugh commented on gm/intermediates.cue
> +			// Details for the certificate used to allow secure traffic to flow
```suggestion
			// TLS certificate defaults, if enabled.
```

2022-08-16 16:14 UTC, dontlaugh commented on gm/intermediates.cue
> +	// Unique topic name for observable audit collection
Add a link to an explanation of "observables" here.

cc @annac-gm the word "observables" is a term we've invented and I don't think anyone outside of this company knows what it is.

2022-08-16 16:14 UTC, dontlaugh commented on gm/intermediates.cue
> +		// This object contains the configuration for filters potentially applied
```suggestion
		// htp_filters contains the configuration for filters potentially applied
```

2022-08-16 16:14 UTC, dontlaugh commented on gm/intermediates.cue
> +		// This list contains the filters which will be active on the listener.
```suggestion
		// The active_http_filters list contains the filters which will be active on the listener.
```

2022-08-16 16:16 UTC, dontlaugh commented on gm/intermediates.cue
> +	if _load_balancer != _|_ {// Allows for configuration of a load balancer, designated by the policy type
Don't introduce more trailing comments. They're harder to maintain.
```suggestion
        // Allows for configuration of a load balancer, designated by the policy type
	if _load_balancer != _|_ {
```

2022-08-16 20:34 UTC, alecholmez commented on gm/intermediates.cue
>  			protocols: [ "TLSv1_2"]
Should we not default to auto? I think that's what envoy does

2022-08-16 20:34 UTC, alecholmez commented on gm/intermediates.cue
> +			// Note: Inheaders and impersonation only function when mTLS is active
Probably want to note that inheaders and impersonation will never be set on the same proxy

2022-08-16 20:34 UTC, alecholmez commented on gm/intermediates.cue
> +#circuit_breaker_default: {// Default values taken from the Envoy documentation
```suggestion
#circuit_breaker_default: { // Default values taken from the Envoy documentation
```

2022-08-16 20:34 UTC, alecholmez commented on gm/intermediates.cue
> +#default_rbac: {// This allows all traffic to flow with no restriction
```suggestion
#default_rbac: { // This allows all traffic to flow with no restriction
```

2022-08-16 20:34 UTC, alecholmez commented on gm/intermediates.cue
> +		keycloak?: {//If Using another provider name below, change this field in your service
```suggestion
		keycloak?: { //If Using another provider name below, change this field in your service
```

2022-08-17 17:50 UTC, tilleryd commented on gm/intermediates.cue
>  			protocols: [ "TLSv1_2"]
I made the change and tested in a deployment and TLS at the edge worked fine with "TLS_AUTO".

2022-08-17 17:54 UTC, alecholmez approved these changes

2022-08-17 18:12 UTC, dontlaugh approved these changes

2022-08-17 18:19 UTC, merged