operator namespace is now configurable through inputs.cue
greymatter-io/gitops-core pull request #60
Opened 2022-08-19 15:40 UTC by alecholmez

Signed-off-by: Alec Holmes <alecholmez@me.com>

2022-08-19 15:47 UTC, jack-bischoff requested changes
1 style fix otherwise good

2022-08-19 15:47 UTC, jack-bischoff commented on inputs.cue
> +	namespace: 					 string | *"gm-operator"
Spacing

2022-08-19 15:49 UTC, danielpcox commented on inputs.cue
> +	namespace: 					 string | *"gm-operator"
I don't like the key name "namespace" for this. There are several relevant namespaces. Can we change it to something less generic, like "operator_namespace"?

2022-08-19 16:38 UTC, alecholmez commented on inputs.cue
> +	namespace: 					 string | *"gm-operator"
Sure thing I can change that.

2022-08-19 17:47 UTC, tilleryd commented on inputs.cue
> +	namespace: 					 string | *"gm-operator"
Do we want to follow the pattern of other fields here? I.e., be overridden via `@tag()`? Also, a comment would be good like `Change this to install the operator into a different namespace.`

2022-08-19 18:16 UTC, alecholmez commented on inputs.cue
> +	namespace: 					 string | *"gm-operator"
You got it, and yea the tag is actually a good idea will add that as well

2022-08-19 19:37 UTC, tilleryd commented
@danielpcox Should this be added to https://github.com/greymatter-io/gitops-core/blob/main/k8s/outputs/operator.cue#L367-L373?

2022-08-19 20:49 UTC, danielpcox commented
That file is currently only used by the integration tests. So if we want to swap the operator namespace in the integration tests, yes. Otherwise no point.

2022-08-19 20:49 UTC, tilleryd commented
Cool, then I will approve this.

2022-08-19 20:49 UTC, tilleryd approved these changes

2022-08-22 14:06 UTC, jack-bischoff approved these changes

2022-08-22 14:11 UTC, merged