Sidecar injection by reconciliation
greymatter-io/gitops-core pull request #67
Opened 2022-08-29 16:46 UTC by danielpcox

[sc-22489]

Companion PR to https://github.com/greymatter-io/operator/pull/151

2022-08-29 20:33 UTC, alecholmez requested changes
Just some minor things

2022-08-29 22:03 UTC, danielpcox commented on inputs.cue
> +	proxy_port_name:        "proxy"
Good plan, I'll add a comment.

2022-08-29 22:04 UTC, danielpcox commented on inputs.cue
> +  gitops_state_key_k8s:     "k8sHashes" // the key in Redis for K8s applied-state backups
K

2022-08-29 22:06 UTC, danielpcox commented on inputs.cue
> +  gitops_state_key_k8s:     "k8sHashes" // the key in Redis for K8s applied-state backups
It doesn't actually look like this in my editor, if you're referring to the `gitops_state_key_k8s` key. I suspect this is just diff weirdness. If you're referring to the alignment of all the rest of the values, I've fixed that now. 👌

2022-08-29 22:59 UTC, alecholmez submitted a review, later dismissed
This looks good to me now

2022-08-31 18:00 UTC, alecholmez approved these changes

2022-08-31 18:00 UTC, merged