WIP Unify oidc-auth filter with generated definition
greymatter-io/gitops-core pull request #77
Opened 2022-09-09 20:45 UTC by jack-bischoff

This allows the intermediate definition to track the actual generated definitions from the proxy. In particular, this allows the user to access the authRealms and authAdminRealms fields necessary for keycloak backwards compatibility.

2022-09-13 21:10 UTC, alecholmez submitted a review, later dismissed

2022-09-14 13:32 UTC, tilleryd commented on inputs.cue
> +				// does not include "auth".
Let's move this into intermediates.cue and use conditional logic to create the URI.

2022-09-14 13:36 UTC, tilleryd commented on gm/intermediates.cue
> +	_legacy_keycloak: bool | *false
I think the term "legacy" is subjective. Two versions behind latest isn't that far back to call it legacy. Perhaps when customers are as far back as 9.x we can call it legacy. I think we should be very specific about when the auth URLs changed. So perhaps we name this field `keycloak_pre_17`.

2022-09-14 13:47 UTC, tilleryd commented on inputs.cue
> +				// does not include "auth".
Can you do something about the URI in the remote_jwks configuration as well? i.e. is there not a single property that can be referenced which is conditionally built to have the value of `"\(endpoint)/auth/realms/\(realm)` or `"\(endpoint)/realms/\(realm)`?

2022-09-14 13:50 UTC, tilleryd commented
This line will need to be addressed as well https://github.com/greymatter-io/gitops-core/blob/main/k8s/outputs/dashboard.cue#L53.

2022-09-14 13:55 UTC, tilleryd commented
Please add a changelog entry/

2022-09-14 14:22 UTC, tilleryd requested changes
A few things to address.

2022-09-14 19:28 UTC, tilleryd commented on CHANGELOG.md
> +- Added support for keycloak pre-v17
```suggestion
- Updated `gm_oidc-authentication` filter to support pre/post Keycloak v17 
```

2022-09-14 19:34 UTC, tilleryd commented
These are great updates. A big improvement on having to string replace auth URLs in multiple places.

2022-09-15 13:50 UTC, tilleryd approved these changes

2022-09-15 14:44 UTC, merged