Enable mtls connections for all internal core components
greymatter-io/gitops-core pull request #85
Opened 2022-09-20 15:57 UTC by moosecanswim

Enable mtls for internal mesh components requires tls to be enabled on the edge node.  See docs PR https://github.com/greymatter-io/gm-docs/pull/125.

The default behavior is to re-use the edge ingress secret's data however you can set up a different cert for external tls and internal mTls.

[sc-26117]

2022-09-20 20:13 UTC, alecholmez requested changes

2022-09-20 20:13 UTC, alecholmez commented on gm/intermediates.cue
> +	if _force_https==true || (strings.Contains(domain_key, "_local") && defaults.edge.enable_tls){
I think this only works for operator configured sidecars no?

We can't guarantee that domain names are `_local` in a `greymatter init` generated project. Are there other ways we can denote that this is an ingress? Is `_force_https` not adequate?

2022-09-20 20:13 UTC, alecholmez commented on k8s/intermediates.cue
> +	if defaults.edge.enable_tls {
This looks like it just makes the mounts for the edge. What about the sidecar injection template?

2022-09-20 20:20 UTC, alecholmez commented
@tilleryd I tagged you on this as well since you're familiar with the mTLS stuff

2022-09-21 14:36 UTC, moosecanswim commented on k8s/intermediates.cue
> +	if defaults.edge.enable_tls {
I agree we should move to just a `defaults.enable_tls` however that would require changing a lot of things (docs + all references) so i figured i'd just piggy back on edge enable tls.

Left a comment here https://github.com/greymatter-io/gitops-core/blob/mtls-internal-010-base/inputs.cue#L120

Also, there is not a good use case for having non tls external and tls internal.

2022-09-21 14:45 UTC, moosecanswim commented on gm/intermediates.cue
> +	if _force_https==true || (strings.Contains(domain_key, "_local") && defaults.edge.enable_tls){
Yeah i've thought about this quite a bit.  _force_https is adequate however it does add lots of redundant references across the in service.cue files.  

Since gitops core only deploys the core components it does not actually matter what `greymatter init` does.  Unless im missing a connection between the two.

2022-09-21 16:39 UTC, alecholmez commented on gm/intermediates.cue
> +	if _force_https==true || (strings.Contains(domain_key, "_local") && defaults.edge.enable_tls){
Hm how bad is the redundancy?

gitops-core also is what determines what init's intermediates file looks like. So it needs to be harmonious. Init embeds `gm/intermediates.cue`

2022-09-21 19:50 UTC, moosecanswim commented on k8s/intermediates.cue
> +	if defaults.edge.enable_tls {
There is a ticket for optimizing the flow of input.cue and intermediate.cue https://app.shortcut.com/grey-matter/story/24607/optimize-inputs-cue-and-service-cue-files

we could add this as a proposed change.

2022-09-21 20:33 UTC, alecholmez commented on gm/intermediates.cue
> +	if _force_https==true || (strings.Contains(domain_key, "_local") && defaults.edge.enable_tls){
Okay per a meeting with kyle we're going to coalesce here and change the init templates and rename this key match. Init will output ingress domains and listeners with a `-ingress` suffix.

This will satisfy the smart key matching system Kyle has in place and also guide users on what to do with init.

2022-09-26 15:27 UTC, alecholmez commented
@moosecanswim approving this. I was able to deploy mtls with an init project and operator v0.10.0 rather smoothly.

The only thing to note right now is you have to manually create the edge-ingress-cert secret in all the watched namespaces. I'll open an issue for that.

2022-09-26 15:27 UTC, alecholmez approved these changes

2022-09-26 15:40 UTC, merged

2022-09-26 17:13 UTC, moosecanswim commented
@alecholmez re: The only thing to note right now is you have to manually create the edge-ingress-cert secret in all the watched namespaces. I'll open an issue for that.

That should be a documentation step not an automated action since if internal mtls is used then the customers will want to use different certs across namespaces for the rbac features that adds.